server:
  port: 8971

#spring:
#  profiles:
#    active: prod
#---
#spring:
#  profiles: dev
#  data.mongodb:
#    host: localhost
#    port: 27017
#    database: local
#---
#spring:
#  profiles: prod
#  host: localhost
#  port: 27017
#  database: local
#---
